### ISSUE TITLE
Poll Implementation Service

### ISSUE THREAD

**Issue by ola-lekan01** [ola-lekan01/Smart-Voting-System#48]
Good Morning Associate,

I pointed out some issues on Poll Implementation services, Please review. 

Thanks, Associate..

**Comment by ola-lekan01** [comment]
So You can just pull the new code from in-dev, I highlighted them in a todo in Poll Service Implementation Class.

**Comment by KabirYusuf** [comment]
Alright Mr. Lekan. Thanks

**Comment by ola-lekan01** [comment]
Thanks for the update...
